//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ges_Muestra
    {
        public int IdEncuesta { get; set; }
        public int RolEstablecimiento { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string Observacion { get; set; }
    
        public virtual Dir_Establecimientos Dir_Establecimientos { get; set; }
        public virtual Ges_Encuestas Ges_Encuestas { get; set; }
    }
}
