//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ges_Informante
    {
        public int RolEstablecimiento { get; set; }
        public string NombreInformante { get; set; }
        public string FonoInformante { get; set; }
        public string CorreoInformante { get; set; }
        public string CargoInformante { get; set; }
    
        public virtual Dir_Establecimientos Dir_Establecimientos { get; set; }
    }
}
