//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glo_Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glo_Clase()
        {
            this.Dir_Establecimientos = new HashSet<Dir_Establecimientos>();
        }
    
        public int IdActividad { get; set; }
        public int IdGrupo { get; set; }
        public string GlosaClase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dir_Establecimientos> Dir_Establecimientos { get; set; }
        public virtual Glo_Grupo Glo_Grupo { get; set; }
    }
}
