//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glo_TipoEncuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glo_TipoEncuesta()
        {
            this.Ges_Encuestas = new HashSet<Ges_Encuestas>();
        }
    
        public int IdTipoEncuesta { get; set; }
        public string GlosaTipoEncuesta { get; set; }
        public string Periodicidad { get; set; }
        public string Publicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ges_Encuestas> Ges_Encuestas { get; set; }
    }
}
