//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Error
    {
        public int IdLogError { get; set; }
        public string Login { get; set; }
        public string Tipo { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> FechaLogError { get; set; }
        public string Pagina { get; set; }
        public string Metodo { get; set; }
    
        public virtual Ges_Usuario Ges_Usuario { get; set; }
    }
}
