//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Evento
    {
        public int IdLogEvento { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> FechaEvento { get; set; }
        public string MensajeEvento { get; set; }
        public string PaginaEvento { get; set; }
        public string MetodoEvento { get; set; }
    
        public virtual Ges_Usuario Ges_Usuario { get; set; }
    }
}
