//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Dir_Empresas> Dir_Empresas { get; set; }
        public virtual DbSet<Dir_Establecimientos> Dir_Establecimientos { get; set; }
        public virtual DbSet<Dir_EstablecimientosTemporales> Dir_EstablecimientosTemporales { get; set; }
        public virtual DbSet<Ges_EncuestaAE> Ges_EncuestaAE { get; set; }
        public virtual DbSet<Ges_Encuestas> Ges_Encuestas { get; set; }
        public virtual DbSet<Ges_Georreferencia> Ges_Georreferencia { get; set; }
        public virtual DbSet<Ges_Informante> Ges_Informante { get; set; }
        public virtual DbSet<Ges_Muestra> Ges_Muestra { get; set; }
        public virtual DbSet<Ges_Usuario> Ges_Usuario { get; set; }
        public virtual DbSet<Glo_Clase> Glo_Clase { get; set; }
        public virtual DbSet<Glo_Comunas> Glo_Comunas { get; set; }
        public virtual DbSet<Glo_Division> Glo_Division { get; set; }
        public virtual DbSet<Glo_EstadoEncuesta> Glo_EstadoEncuesta { get; set; }
        public virtual DbSet<Glo_Estados> Glo_Estados { get; set; }
        public virtual DbSet<Glo_Grupo> Glo_Grupo { get; set; }
        public virtual DbSet<Glo_Provincias> Glo_Provincias { get; set; }
        public virtual DbSet<Glo_Region> Glo_Region { get; set; }
        public virtual DbSet<Glo_Seccion> Glo_Seccion { get; set; }
        public virtual DbSet<Glo_TipoEncuesta> Glo_TipoEncuesta { get; set; }
        public virtual DbSet<Glo_TipoVia> Glo_TipoVia { get; set; }
        public virtual DbSet<Log_Acceso> Log_Acceso { get; set; }
        public virtual DbSet<Log_Error> Log_Error { get; set; }
        public virtual DbSet<Log_Evento> Log_Evento { get; set; }
        public virtual DbSet<Sys_Menu> Sys_Menu { get; set; }
        public virtual DbSet<Sys_Paginas> Sys_Paginas { get; set; }
        public virtual DbSet<Sys_Roles> Sys_Roles { get; set; }
    
        public virtual int Pa_Cls_AccesoLog_Insertar(string login, Nullable<System.DateTime> fechaLogAcceso, string iP)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var fechaLogAccesoParameter = fechaLogAcceso.HasValue ?
                new ObjectParameter("FechaLogAcceso", fechaLogAcceso) :
                new ObjectParameter("FechaLogAcceso", typeof(System.DateTime));
    
            var iPParameter = iP != null ?
                new ObjectParameter("IP", iP) :
                new ObjectParameter("IP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_AccesoLog_Insertar", loginParameter, fechaLogAccesoParameter, iPParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_AccesoLog_Listar_Result> Pa_Cls_AccesoLog_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_AccesoLog_Listar_Result>("Pa_Cls_AccesoLog_Listar");
        }
    
        public virtual ObjectResult<Pa_Cls_ActividadGlo_Listar_Result> Pa_Cls_ActividadGlo_Listar(Nullable<int> idSubClase)
        {
            var idSubClaseParameter = idSubClase.HasValue ?
                new ObjectParameter("IdSubClase", idSubClase) :
                new ObjectParameter("IdSubClase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ActividadGlo_Listar_Result>("Pa_Cls_ActividadGlo_Listar", idSubClaseParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_ClaseGlo_Listar_Result> Pa_Cls_ClaseGlo_Listar(Nullable<int> idGrupo)
        {
            var idGrupoParameter = idGrupo.HasValue ?
                new ObjectParameter("IdGrupo", idGrupo) :
                new ObjectParameter("IdGrupo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ClaseGlo_Listar_Result>("Pa_Cls_ClaseGlo_Listar", idGrupoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_ComunasGlo_Listar_Result> Pa_Cls_ComunasGlo_Listar(Nullable<int> codProvincia)
        {
            var codProvinciaParameter = codProvincia.HasValue ?
                new ObjectParameter("CodProvincia", codProvincia) :
                new ObjectParameter("CodProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ComunasGlo_Listar_Result>("Pa_Cls_ComunasGlo_Listar", codProvinciaParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_ComunasGlo_ListarOctava_Result> Pa_Cls_ComunasGlo_ListarOctava()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ComunasGlo_ListarOctava_Result>("Pa_Cls_ComunasGlo_ListarOctava");
        }
    
        public virtual ObjectResult<Pa_Cls_DivisionGlo_Listar_Result> Pa_Cls_DivisionGlo_Listar(string idSeccion)
        {
            var idSeccionParameter = idSeccion != null ?
                new ObjectParameter("IdSeccion", idSeccion) :
                new ObjectParameter("IdSeccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_DivisionGlo_Listar_Result>("Pa_Cls_DivisionGlo_Listar", idSeccionParameter);
        }
    
        public virtual int Pa_Cls_EmpresasDir_Insertar(Nullable<int> rutEmpresa, Nullable<int> codComuna, string dvEmpresa, string razonSocial, string representanteLegal, Nullable<int> idEstado)
        {
            var rutEmpresaParameter = rutEmpresa.HasValue ?
                new ObjectParameter("RutEmpresa", rutEmpresa) :
                new ObjectParameter("RutEmpresa", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var dvEmpresaParameter = dvEmpresa != null ?
                new ObjectParameter("DvEmpresa", dvEmpresa) :
                new ObjectParameter("DvEmpresa", typeof(string));
    
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            var representanteLegalParameter = representanteLegal != null ?
                new ObjectParameter("RepresentanteLegal", representanteLegal) :
                new ObjectParameter("RepresentanteLegal", typeof(string));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EmpresasDir_Insertar", rutEmpresaParameter, codComunaParameter, dvEmpresaParameter, razonSocialParameter, representanteLegalParameter, idEstadoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EmpresasDir_Listar_Result> Pa_Cls_EmpresasDir_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EmpresasDir_Listar_Result>("Pa_Cls_EmpresasDir_Listar");
        }
    
        public virtual int Pa_Cls_EmpresasDir_Modificar(Nullable<int> rutEmpresa, Nullable<int> codComuna, string dvEmpresa, string razonSocial, string representanteLegal, Nullable<int> idEstado)
        {
            var rutEmpresaParameter = rutEmpresa.HasValue ?
                new ObjectParameter("RutEmpresa", rutEmpresa) :
                new ObjectParameter("RutEmpresa", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var dvEmpresaParameter = dvEmpresa != null ?
                new ObjectParameter("DvEmpresa", dvEmpresa) :
                new ObjectParameter("DvEmpresa", typeof(string));
    
            var razonSocialParameter = razonSocial != null ?
                new ObjectParameter("RazonSocial", razonSocial) :
                new ObjectParameter("RazonSocial", typeof(string));
    
            var representanteLegalParameter = representanteLegal != null ?
                new ObjectParameter("RepresentanteLegal", representanteLegal) :
                new ObjectParameter("RepresentanteLegal", typeof(string));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EmpresasDir_Modificar", rutEmpresaParameter, codComunaParameter, dvEmpresaParameter, razonSocialParameter, representanteLegalParameter, idEstadoParameter);
        }
    
        public virtual int Pa_Cls_EncuestaAEGes_Eliminar(Nullable<int> idEncuesta, Nullable<int> idActividad)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EncuestaAEGes_Eliminar", idEncuestaParameter, idActividadParameter);
        }
    
        public virtual int Pa_Cls_EncuestaAEGes_Insertar(Nullable<int> idEncuesta, Nullable<int> idActividad)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EncuestaAEGes_Insertar", idEncuestaParameter, idActividadParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EncuestaAEGes_Listar_Result> Pa_Cls_EncuestaAEGes_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EncuestaAEGes_Listar_Result>("Pa_Cls_EncuestaAEGes_Listar");
        }
    
        public virtual int Pa_Cls_EncuestasGes_Insertar(Nullable<int> idEstadoEncuesta, string nombreEncuesta, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaTermino)
        {
            var idEstadoEncuestaParameter = idEstadoEncuesta.HasValue ?
                new ObjectParameter("IdEstadoEncuesta", idEstadoEncuesta) :
                new ObjectParameter("IdEstadoEncuesta", typeof(int));
    
            var nombreEncuestaParameter = nombreEncuesta != null ?
                new ObjectParameter("NombreEncuesta", nombreEncuesta) :
                new ObjectParameter("NombreEncuesta", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaTerminoParameter = fechaTermino.HasValue ?
                new ObjectParameter("FechaTermino", fechaTermino) :
                new ObjectParameter("FechaTermino", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EncuestasGes_Insertar", idEstadoEncuestaParameter, nombreEncuestaParameter, fechaInicioParameter, fechaTerminoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EncuestasGes_Listar_Result> Pa_Cls_EncuestasGes_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EncuestasGes_Listar_Result>("Pa_Cls_EncuestasGes_Listar");
        }
    
        public virtual ObjectResult<Pa_Cls_EncuestasGes_ListarActivas_Result> Pa_Cls_EncuestasGes_ListarActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EncuestasGes_ListarActivas_Result>("Pa_Cls_EncuestasGes_ListarActivas");
        }
    
        public virtual ObjectResult<Pa_Cls_EncuestasGes_ListarEstablecimientos_Result> Pa_Cls_EncuestasGes_ListarEstablecimientos(Nullable<int> idEncuesta)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EncuestasGes_ListarEstablecimientos_Result>("Pa_Cls_EncuestasGes_ListarEstablecimientos", idEncuestaParameter);
        }
    
        public virtual int Pa_Cls_EncuestasGes_Modificar(Nullable<int> idEncuesta, Nullable<int> idEstadoEncuesta, string nombreEncuesta, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaTermino)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var idEstadoEncuestaParameter = idEstadoEncuesta.HasValue ?
                new ObjectParameter("IdEstadoEncuesta", idEstadoEncuesta) :
                new ObjectParameter("IdEstadoEncuesta", typeof(int));
    
            var nombreEncuestaParameter = nombreEncuesta != null ?
                new ObjectParameter("NombreEncuesta", nombreEncuesta) :
                new ObjectParameter("NombreEncuesta", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaTerminoParameter = fechaTermino.HasValue ?
                new ObjectParameter("FechaTermino", fechaTermino) :
                new ObjectParameter("FechaTermino", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EncuestasGes_Modificar", idEncuestaParameter, idEstadoEncuestaParameter, nombreEncuestaParameter, fechaInicioParameter, fechaTerminoParameter);
        }
    
        public virtual int Pa_Cls_ErrorLog_Insertar(string login, string tipo, string pagina, string mensaje, string metodo, Nullable<System.DateTime> fechaLogError)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var paginaParameter = pagina != null ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(string));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var metodoParameter = metodo != null ?
                new ObjectParameter("Metodo", metodo) :
                new ObjectParameter("Metodo", typeof(string));
    
            var fechaLogErrorParameter = fechaLogError.HasValue ?
                new ObjectParameter("FechaLogError", fechaLogError) :
                new ObjectParameter("FechaLogError", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_ErrorLog_Insertar", loginParameter, tipoParameter, paginaParameter, mensajeParameter, metodoParameter, fechaLogErrorParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_ErrorLog_Listar_Result> Pa_Cls_ErrorLog_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ErrorLog_Listar_Result>("Pa_Cls_ErrorLog_Listar");
        }
    
        public virtual int Pa_Cls_EstablecimientosDir_Insertar(Nullable<int> rolEstablecimiento, Nullable<int> codTipoVia, Nullable<int> idActividad, Nullable<int> idEstado, Nullable<int> codComuna, Nullable<int> rutEmpresa, string dvEstablecimiento, string direccionEstablecimiento, string numeroEstablecimiento, string restoDireccion, string codigoArea1, string telefono1, string codigoArea2, string telefono2, string codigoArea3, string telefono3, string correoElectronico, string sitioWeb, string casilla, string observacion, string nombreEstablecimiento)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var codTipoViaParameter = codTipoVia.HasValue ?
                new ObjectParameter("CodTipoVia", codTipoVia) :
                new ObjectParameter("CodTipoVia", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var rutEmpresaParameter = rutEmpresa.HasValue ?
                new ObjectParameter("RutEmpresa", rutEmpresa) :
                new ObjectParameter("RutEmpresa", typeof(int));
    
            var dvEstablecimientoParameter = dvEstablecimiento != null ?
                new ObjectParameter("DvEstablecimiento", dvEstablecimiento) :
                new ObjectParameter("DvEstablecimiento", typeof(string));
    
            var direccionEstablecimientoParameter = direccionEstablecimiento != null ?
                new ObjectParameter("DireccionEstablecimiento", direccionEstablecimiento) :
                new ObjectParameter("DireccionEstablecimiento", typeof(string));
    
            var numeroEstablecimientoParameter = numeroEstablecimiento != null ?
                new ObjectParameter("NumeroEstablecimiento", numeroEstablecimiento) :
                new ObjectParameter("NumeroEstablecimiento", typeof(string));
    
            var restoDireccionParameter = restoDireccion != null ?
                new ObjectParameter("RestoDireccion", restoDireccion) :
                new ObjectParameter("RestoDireccion", typeof(string));
    
            var codigoArea1Parameter = codigoArea1 != null ?
                new ObjectParameter("CodigoArea1", codigoArea1) :
                new ObjectParameter("CodigoArea1", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var codigoArea2Parameter = codigoArea2 != null ?
                new ObjectParameter("CodigoArea2", codigoArea2) :
                new ObjectParameter("CodigoArea2", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var codigoArea3Parameter = codigoArea3 != null ?
                new ObjectParameter("CodigoArea3", codigoArea3) :
                new ObjectParameter("CodigoArea3", typeof(string));
    
            var telefono3Parameter = telefono3 != null ?
                new ObjectParameter("Telefono3", telefono3) :
                new ObjectParameter("Telefono3", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var sitioWebParameter = sitioWeb != null ?
                new ObjectParameter("SitioWeb", sitioWeb) :
                new ObjectParameter("SitioWeb", typeof(string));
    
            var casillaParameter = casilla != null ?
                new ObjectParameter("Casilla", casilla) :
                new ObjectParameter("Casilla", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var nombreEstablecimientoParameter = nombreEstablecimiento != null ?
                new ObjectParameter("NombreEstablecimiento", nombreEstablecimiento) :
                new ObjectParameter("NombreEstablecimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosDir_Insertar", rolEstablecimientoParameter, codTipoViaParameter, idActividadParameter, idEstadoParameter, codComunaParameter, rutEmpresaParameter, dvEstablecimientoParameter, direccionEstablecimientoParameter, numeroEstablecimientoParameter, restoDireccionParameter, codigoArea1Parameter, telefono1Parameter, codigoArea2Parameter, telefono2Parameter, codigoArea3Parameter, telefono3Parameter, correoElectronicoParameter, sitioWebParameter, casillaParameter, observacionParameter, nombreEstablecimientoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EstablecimientosDir_Listar_Result> Pa_Cls_EstablecimientosDir_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstablecimientosDir_Listar_Result>("Pa_Cls_EstablecimientosDir_Listar");
        }
    
        public virtual int Pa_Cls_EstablecimientosDir_Modificar(Nullable<int> rolEstablecimiento, Nullable<int> codTipoVia, Nullable<int> idActividad, Nullable<int> idEstado, Nullable<int> codComuna, string direccionEstablecimiento, string numeroEstablecimiento, string restoDireccion, string codigoArea1, string telefono1, string codigoArea2, string telefono2, string codigoArea3, string telefono3, string correoElectronico, string sitioWeb, string casilla, string observacion, string nombreEstablecimiento)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var codTipoViaParameter = codTipoVia.HasValue ?
                new ObjectParameter("CodTipoVia", codTipoVia) :
                new ObjectParameter("CodTipoVia", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var direccionEstablecimientoParameter = direccionEstablecimiento != null ?
                new ObjectParameter("DireccionEstablecimiento", direccionEstablecimiento) :
                new ObjectParameter("DireccionEstablecimiento", typeof(string));
    
            var numeroEstablecimientoParameter = numeroEstablecimiento != null ?
                new ObjectParameter("NumeroEstablecimiento", numeroEstablecimiento) :
                new ObjectParameter("NumeroEstablecimiento", typeof(string));
    
            var restoDireccionParameter = restoDireccion != null ?
                new ObjectParameter("RestoDireccion", restoDireccion) :
                new ObjectParameter("RestoDireccion", typeof(string));
    
            var codigoArea1Parameter = codigoArea1 != null ?
                new ObjectParameter("CodigoArea1", codigoArea1) :
                new ObjectParameter("CodigoArea1", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var codigoArea2Parameter = codigoArea2 != null ?
                new ObjectParameter("CodigoArea2", codigoArea2) :
                new ObjectParameter("CodigoArea2", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var codigoArea3Parameter = codigoArea3 != null ?
                new ObjectParameter("CodigoArea3", codigoArea3) :
                new ObjectParameter("CodigoArea3", typeof(string));
    
            var telefono3Parameter = telefono3 != null ?
                new ObjectParameter("Telefono3", telefono3) :
                new ObjectParameter("Telefono3", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var sitioWebParameter = sitioWeb != null ?
                new ObjectParameter("SitioWeb", sitioWeb) :
                new ObjectParameter("SitioWeb", typeof(string));
    
            var casillaParameter = casilla != null ?
                new ObjectParameter("Casilla", casilla) :
                new ObjectParameter("Casilla", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var nombreEstablecimientoParameter = nombreEstablecimiento != null ?
                new ObjectParameter("NombreEstablecimiento", nombreEstablecimiento) :
                new ObjectParameter("NombreEstablecimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosDir_Modificar", rolEstablecimientoParameter, codTipoViaParameter, idActividadParameter, idEstadoParameter, codComunaParameter, direccionEstablecimientoParameter, numeroEstablecimientoParameter, restoDireccionParameter, codigoArea1Parameter, telefono1Parameter, codigoArea2Parameter, telefono2Parameter, codigoArea3Parameter, telefono3Parameter, correoElectronicoParameter, sitioWebParameter, casillaParameter, observacionParameter, nombreEstablecimientoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EstablecimientosDir_Reporte_Result> Pa_Cls_EstablecimientosDir_Reporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstablecimientosDir_Reporte_Result>("Pa_Cls_EstablecimientosDir_Reporte");
        }
    
        public virtual int Pa_Cls_EstablecimientosTemporalesDir_Eliminar(Nullable<int> idEstablecimiento)
        {
            var idEstablecimientoParameter = idEstablecimiento.HasValue ?
                new ObjectParameter("IdEstablecimiento", idEstablecimiento) :
                new ObjectParameter("IdEstablecimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosTemporalesDir_Eliminar", idEstablecimientoParameter);
        }
    
        public virtual int Pa_Cls_EstablecimientosTemporalesDir_Insertar(Nullable<int> rutEmpresa, Nullable<int> codComuna, Nullable<int> idEstado, Nullable<int> codTipoVia, Nullable<int> idActividad, string direccionEstablecimientoTemp, string numeroEstablecimientoTemp, string restoDireccionTemp, string codigoArea1Temp, string telefono1Temp, string codigoArea2Temp, string telefono2Temp, string codigoArea3Temp, string telefono3Temp, string correoElectronicoTemp, string sitioWebTemp, string casillaTemp, string observacionTemp, string nombreEstablecimientoTemp, string nombreInformanteTemp, string fonoInformanteTemp, string correoInformanteTemp, string cargoInformanteTemp)
        {
            var rutEmpresaParameter = rutEmpresa.HasValue ?
                new ObjectParameter("RutEmpresa", rutEmpresa) :
                new ObjectParameter("RutEmpresa", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var codTipoViaParameter = codTipoVia.HasValue ?
                new ObjectParameter("CodTipoVia", codTipoVia) :
                new ObjectParameter("CodTipoVia", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            var direccionEstablecimientoTempParameter = direccionEstablecimientoTemp != null ?
                new ObjectParameter("DireccionEstablecimientoTemp", direccionEstablecimientoTemp) :
                new ObjectParameter("DireccionEstablecimientoTemp", typeof(string));
    
            var numeroEstablecimientoTempParameter = numeroEstablecimientoTemp != null ?
                new ObjectParameter("NumeroEstablecimientoTemp", numeroEstablecimientoTemp) :
                new ObjectParameter("NumeroEstablecimientoTemp", typeof(string));
    
            var restoDireccionTempParameter = restoDireccionTemp != null ?
                new ObjectParameter("RestoDireccionTemp", restoDireccionTemp) :
                new ObjectParameter("RestoDireccionTemp", typeof(string));
    
            var codigoArea1TempParameter = codigoArea1Temp != null ?
                new ObjectParameter("CodigoArea1Temp", codigoArea1Temp) :
                new ObjectParameter("CodigoArea1Temp", typeof(string));
    
            var telefono1TempParameter = telefono1Temp != null ?
                new ObjectParameter("Telefono1Temp", telefono1Temp) :
                new ObjectParameter("Telefono1Temp", typeof(string));
    
            var codigoArea2TempParameter = codigoArea2Temp != null ?
                new ObjectParameter("CodigoArea2Temp", codigoArea2Temp) :
                new ObjectParameter("CodigoArea2Temp", typeof(string));
    
            var telefono2TempParameter = telefono2Temp != null ?
                new ObjectParameter("Telefono2Temp", telefono2Temp) :
                new ObjectParameter("Telefono2Temp", typeof(string));
    
            var codigoArea3TempParameter = codigoArea3Temp != null ?
                new ObjectParameter("CodigoArea3Temp", codigoArea3Temp) :
                new ObjectParameter("CodigoArea3Temp", typeof(string));
    
            var telefono3TempParameter = telefono3Temp != null ?
                new ObjectParameter("Telefono3Temp", telefono3Temp) :
                new ObjectParameter("Telefono3Temp", typeof(string));
    
            var correoElectronicoTempParameter = correoElectronicoTemp != null ?
                new ObjectParameter("CorreoElectronicoTemp", correoElectronicoTemp) :
                new ObjectParameter("CorreoElectronicoTemp", typeof(string));
    
            var sitioWebTempParameter = sitioWebTemp != null ?
                new ObjectParameter("SitioWebTemp", sitioWebTemp) :
                new ObjectParameter("SitioWebTemp", typeof(string));
    
            var casillaTempParameter = casillaTemp != null ?
                new ObjectParameter("CasillaTemp", casillaTemp) :
                new ObjectParameter("CasillaTemp", typeof(string));
    
            var observacionTempParameter = observacionTemp != null ?
                new ObjectParameter("ObservacionTemp", observacionTemp) :
                new ObjectParameter("ObservacionTemp", typeof(string));
    
            var nombreEstablecimientoTempParameter = nombreEstablecimientoTemp != null ?
                new ObjectParameter("NombreEstablecimientoTemp", nombreEstablecimientoTemp) :
                new ObjectParameter("NombreEstablecimientoTemp", typeof(string));
    
            var nombreInformanteTempParameter = nombreInformanteTemp != null ?
                new ObjectParameter("NombreInformanteTemp", nombreInformanteTemp) :
                new ObjectParameter("NombreInformanteTemp", typeof(string));
    
            var fonoInformanteTempParameter = fonoInformanteTemp != null ?
                new ObjectParameter("FonoInformanteTemp", fonoInformanteTemp) :
                new ObjectParameter("FonoInformanteTemp", typeof(string));
    
            var correoInformanteTempParameter = correoInformanteTemp != null ?
                new ObjectParameter("CorreoInformanteTemp", correoInformanteTemp) :
                new ObjectParameter("CorreoInformanteTemp", typeof(string));
    
            var cargoInformanteTempParameter = cargoInformanteTemp != null ?
                new ObjectParameter("CargoInformanteTemp", cargoInformanteTemp) :
                new ObjectParameter("CargoInformanteTemp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosTemporalesDir_Insertar", rutEmpresaParameter, codComunaParameter, idEstadoParameter, codTipoViaParameter, idActividadParameter, direccionEstablecimientoTempParameter, numeroEstablecimientoTempParameter, restoDireccionTempParameter, codigoArea1TempParameter, telefono1TempParameter, codigoArea2TempParameter, telefono2TempParameter, codigoArea3TempParameter, telefono3TempParameter, correoElectronicoTempParameter, sitioWebTempParameter, casillaTempParameter, observacionTempParameter, nombreEstablecimientoTempParameter, nombreInformanteTempParameter, fonoInformanteTempParameter, correoInformanteTempParameter, cargoInformanteTempParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EstablecimientosTemporalesDir_Listar_Result> Pa_Cls_EstablecimientosTemporalesDir_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstablecimientosTemporalesDir_Listar_Result>("Pa_Cls_EstablecimientosTemporalesDir_Listar");
        }
    
        public virtual int Pa_Cls_EstablecimientosTemporalesDir_Modificar(Nullable<int> idEstablecimiento, Nullable<int> rutEmpresa, Nullable<int> codComuna, Nullable<int> idEstado, Nullable<int> codTipoVia, Nullable<int> idActividad, string direccionEstablecimientoTemp, string numeroEstablecimientoTemp, string restoDireccionTemp, string codigoArea1Temp, string telefono1Temp, string codigoArea2Temp, string telefono2Temp, string codigoArea3Temp, string telefono3Temp, string correoElectronicoTemp, string sitioWebTemp, string casillaTemp, string observacionTemp, string nombreEstablecimientoTemp, string nombreInformanteTemp, string fonoInformanteTemp, string correoInformanteTemp, string cargoInformanteTemp)
        {
            var idEstablecimientoParameter = idEstablecimiento.HasValue ?
                new ObjectParameter("IdEstablecimiento", idEstablecimiento) :
                new ObjectParameter("IdEstablecimiento", typeof(int));
    
            var rutEmpresaParameter = rutEmpresa.HasValue ?
                new ObjectParameter("RutEmpresa", rutEmpresa) :
                new ObjectParameter("RutEmpresa", typeof(int));
    
            var codComunaParameter = codComuna.HasValue ?
                new ObjectParameter("CodComuna", codComuna) :
                new ObjectParameter("CodComuna", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var codTipoViaParameter = codTipoVia.HasValue ?
                new ObjectParameter("CodTipoVia", codTipoVia) :
                new ObjectParameter("CodTipoVia", typeof(int));
    
            var idActividadParameter = idActividad.HasValue ?
                new ObjectParameter("IdActividad", idActividad) :
                new ObjectParameter("IdActividad", typeof(int));
    
            var direccionEstablecimientoTempParameter = direccionEstablecimientoTemp != null ?
                new ObjectParameter("DireccionEstablecimientoTemp", direccionEstablecimientoTemp) :
                new ObjectParameter("DireccionEstablecimientoTemp", typeof(string));
    
            var numeroEstablecimientoTempParameter = numeroEstablecimientoTemp != null ?
                new ObjectParameter("NumeroEstablecimientoTemp", numeroEstablecimientoTemp) :
                new ObjectParameter("NumeroEstablecimientoTemp", typeof(string));
    
            var restoDireccionTempParameter = restoDireccionTemp != null ?
                new ObjectParameter("RestoDireccionTemp", restoDireccionTemp) :
                new ObjectParameter("RestoDireccionTemp", typeof(string));
    
            var codigoArea1TempParameter = codigoArea1Temp != null ?
                new ObjectParameter("CodigoArea1Temp", codigoArea1Temp) :
                new ObjectParameter("CodigoArea1Temp", typeof(string));
    
            var telefono1TempParameter = telefono1Temp != null ?
                new ObjectParameter("Telefono1Temp", telefono1Temp) :
                new ObjectParameter("Telefono1Temp", typeof(string));
    
            var codigoArea2TempParameter = codigoArea2Temp != null ?
                new ObjectParameter("CodigoArea2Temp", codigoArea2Temp) :
                new ObjectParameter("CodigoArea2Temp", typeof(string));
    
            var telefono2TempParameter = telefono2Temp != null ?
                new ObjectParameter("Telefono2Temp", telefono2Temp) :
                new ObjectParameter("Telefono2Temp", typeof(string));
    
            var codigoArea3TempParameter = codigoArea3Temp != null ?
                new ObjectParameter("CodigoArea3Temp", codigoArea3Temp) :
                new ObjectParameter("CodigoArea3Temp", typeof(string));
    
            var telefono3TempParameter = telefono3Temp != null ?
                new ObjectParameter("Telefono3Temp", telefono3Temp) :
                new ObjectParameter("Telefono3Temp", typeof(string));
    
            var correoElectronicoTempParameter = correoElectronicoTemp != null ?
                new ObjectParameter("CorreoElectronicoTemp", correoElectronicoTemp) :
                new ObjectParameter("CorreoElectronicoTemp", typeof(string));
    
            var sitioWebTempParameter = sitioWebTemp != null ?
                new ObjectParameter("SitioWebTemp", sitioWebTemp) :
                new ObjectParameter("SitioWebTemp", typeof(string));
    
            var casillaTempParameter = casillaTemp != null ?
                new ObjectParameter("CasillaTemp", casillaTemp) :
                new ObjectParameter("CasillaTemp", typeof(string));
    
            var observacionTempParameter = observacionTemp != null ?
                new ObjectParameter("ObservacionTemp", observacionTemp) :
                new ObjectParameter("ObservacionTemp", typeof(string));
    
            var nombreEstablecimientoTempParameter = nombreEstablecimientoTemp != null ?
                new ObjectParameter("NombreEstablecimientoTemp", nombreEstablecimientoTemp) :
                new ObjectParameter("NombreEstablecimientoTemp", typeof(string));
    
            var nombreInformanteTempParameter = nombreInformanteTemp != null ?
                new ObjectParameter("NombreInformanteTemp", nombreInformanteTemp) :
                new ObjectParameter("NombreInformanteTemp", typeof(string));
    
            var fonoInformanteTempParameter = fonoInformanteTemp != null ?
                new ObjectParameter("FonoInformanteTemp", fonoInformanteTemp) :
                new ObjectParameter("FonoInformanteTemp", typeof(string));
    
            var correoInformanteTempParameter = correoInformanteTemp != null ?
                new ObjectParameter("CorreoInformanteTemp", correoInformanteTemp) :
                new ObjectParameter("CorreoInformanteTemp", typeof(string));
    
            var cargoInformanteTempParameter = cargoInformanteTemp != null ?
                new ObjectParameter("CargoInformanteTemp", cargoInformanteTemp) :
                new ObjectParameter("CargoInformanteTemp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosTemporalesDir_Modificar", idEstablecimientoParameter, rutEmpresaParameter, codComunaParameter, idEstadoParameter, codTipoViaParameter, idActividadParameter, direccionEstablecimientoTempParameter, numeroEstablecimientoTempParameter, restoDireccionTempParameter, codigoArea1TempParameter, telefono1TempParameter, codigoArea2TempParameter, telefono2TempParameter, codigoArea3TempParameter, telefono3TempParameter, correoElectronicoTempParameter, sitioWebTempParameter, casillaTempParameter, observacionTempParameter, nombreEstablecimientoTempParameter, nombreInformanteTempParameter, fonoInformanteTempParameter, correoInformanteTempParameter, cargoInformanteTempParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EstablecimientosTemporalesDir_Reporte_Result> Pa_Cls_EstablecimientosTemporalesDir_Reporte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstablecimientosTemporalesDir_Reporte_Result>("Pa_Cls_EstablecimientosTemporalesDir_Reporte");
        }
    
        public virtual int Pa_Cls_EstablecimientosTemporalesDir_TraspasoEnrolado(Nullable<int> idEstablecimiento, Nullable<int> rolEstablecimiento, string dvEstablecimiento)
        {
            var idEstablecimientoParameter = idEstablecimiento.HasValue ?
                new ObjectParameter("IdEstablecimiento", idEstablecimiento) :
                new ObjectParameter("IdEstablecimiento", typeof(int));
    
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var dvEstablecimientoParameter = dvEstablecimiento != null ?
                new ObjectParameter("DvEstablecimiento", dvEstablecimiento) :
                new ObjectParameter("DvEstablecimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EstablecimientosTemporalesDir_TraspasoEnrolado", idEstablecimientoParameter, rolEstablecimientoParameter, dvEstablecimientoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EstadoEncuestaGlo_Listar_Result> Pa_Cls_EstadoEncuestaGlo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstadoEncuestaGlo_Listar_Result>("Pa_Cls_EstadoEncuestaGlo_Listar");
        }
    
        public virtual ObjectResult<Pa_Cls_EstadosGlo_Listar_Result> Pa_Cls_EstadosGlo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EstadosGlo_Listar_Result>("Pa_Cls_EstadosGlo_Listar");
        }
    
        public virtual int Pa_Cls_EventoLog_Insertar(Nullable<int> idLogEvento, string login, Nullable<System.DateTime> fechaEvento, string mensajeEvento, string paginaEvento, string metodoEvento)
        {
            var idLogEventoParameter = idLogEvento.HasValue ?
                new ObjectParameter("IdLogEvento", idLogEvento) :
                new ObjectParameter("IdLogEvento", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var fechaEventoParameter = fechaEvento.HasValue ?
                new ObjectParameter("FechaEvento", fechaEvento) :
                new ObjectParameter("FechaEvento", typeof(System.DateTime));
    
            var mensajeEventoParameter = mensajeEvento != null ?
                new ObjectParameter("MensajeEvento", mensajeEvento) :
                new ObjectParameter("MensajeEvento", typeof(string));
    
            var paginaEventoParameter = paginaEvento != null ?
                new ObjectParameter("PaginaEvento", paginaEvento) :
                new ObjectParameter("PaginaEvento", typeof(string));
    
            var metodoEventoParameter = metodoEvento != null ?
                new ObjectParameter("MetodoEvento", metodoEvento) :
                new ObjectParameter("MetodoEvento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_EventoLog_Insertar", idLogEventoParameter, loginParameter, fechaEventoParameter, mensajeEventoParameter, paginaEventoParameter, metodoEventoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_EventoLog_Listar_Result> Pa_Cls_EventoLog_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_EventoLog_Listar_Result>("Pa_Cls_EventoLog_Listar");
        }
    
        public virtual int Pa_Cls_GeorreferenciaGes_Eliminar(Nullable<int> rolEstablecimiento)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_GeorreferenciaGes_Eliminar", rolEstablecimientoParameter);
        }
    
        public virtual int Pa_Cls_GeorreferenciaGes_Insertar(Nullable<int> rolEstablecimiento, string latitud, string longitud)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("Latitud", latitud) :
                new ObjectParameter("Latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("Longitud", longitud) :
                new ObjectParameter("Longitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_GeorreferenciaGes_Insertar", rolEstablecimientoParameter, latitudParameter, longitudParameter);
        }
    
        public virtual int Pa_Cls_GeorreferenciaGes_Modificar(Nullable<int> rolEstablecimiento, string latitud, string longitud)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var latitudParameter = latitud != null ?
                new ObjectParameter("Latitud", latitud) :
                new ObjectParameter("Latitud", typeof(string));
    
            var longitudParameter = longitud != null ?
                new ObjectParameter("Longitud", longitud) :
                new ObjectParameter("Longitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_GeorreferenciaGes_Modificar", rolEstablecimientoParameter, latitudParameter, longitudParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_GrupoGlo_Listar_Result> Pa_Cls_GrupoGlo_Listar(Nullable<int> idDivision)
        {
            var idDivisionParameter = idDivision.HasValue ?
                new ObjectParameter("IdDivision", idDivision) :
                new ObjectParameter("IdDivision", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_GrupoGlo_Listar_Result>("Pa_Cls_GrupoGlo_Listar", idDivisionParameter);
        }
    
        public virtual int Pa_Cls_InformanteGes_Insertar(Nullable<int> rolEstablecimiento, string nombreInformante, string fonoInformante, string correoInformante, string cargoInformante)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var nombreInformanteParameter = nombreInformante != null ?
                new ObjectParameter("NombreInformante", nombreInformante) :
                new ObjectParameter("NombreInformante", typeof(string));
    
            var fonoInformanteParameter = fonoInformante != null ?
                new ObjectParameter("FonoInformante", fonoInformante) :
                new ObjectParameter("FonoInformante", typeof(string));
    
            var correoInformanteParameter = correoInformante != null ?
                new ObjectParameter("CorreoInformante", correoInformante) :
                new ObjectParameter("CorreoInformante", typeof(string));
    
            var cargoInformanteParameter = cargoInformante != null ?
                new ObjectParameter("CargoInformante", cargoInformante) :
                new ObjectParameter("CargoInformante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_InformanteGes_Insertar", rolEstablecimientoParameter, nombreInformanteParameter, fonoInformanteParameter, correoInformanteParameter, cargoInformanteParameter);
        }
    
        public virtual int Pa_Cls_InformanteGes_Modificar(Nullable<int> rolEstablecimiento, string nombreInformante, string fonoInformante, string correoInformante, string cargoInformante)
        {
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var nombreInformanteParameter = nombreInformante != null ?
                new ObjectParameter("NombreInformante", nombreInformante) :
                new ObjectParameter("NombreInformante", typeof(string));
    
            var fonoInformanteParameter = fonoInformante != null ?
                new ObjectParameter("FonoInformante", fonoInformante) :
                new ObjectParameter("FonoInformante", typeof(string));
    
            var correoInformanteParameter = correoInformante != null ?
                new ObjectParameter("CorreoInformante", correoInformante) :
                new ObjectParameter("CorreoInformante", typeof(string));
    
            var cargoInformanteParameter = cargoInformante != null ?
                new ObjectParameter("CargoInformante", cargoInformante) :
                new ObjectParameter("CargoInformante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_InformanteGes_Modificar", rolEstablecimientoParameter, nombreInformanteParameter, fonoInformanteParameter, correoInformanteParameter, cargoInformanteParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_MuestraGes_Avance_Result> Pa_Cls_MuestraGes_Avance(Nullable<int> idEncuesta)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_MuestraGes_Avance_Result>("Pa_Cls_MuestraGes_Avance", idEncuestaParameter);
        }
    
        public virtual int Pa_Cls_MuestraGes_Eliminar(Nullable<int> idEncuesta, Nullable<int> rolEstablecimiento)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_MuestraGes_Eliminar", idEncuestaParameter, rolEstablecimientoParameter);
        }
    
        public virtual int Pa_Cls_MuestraGes_Insertar(Nullable<int> idEncuesta, Nullable<int> rolEstablecimiento)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_MuestraGes_Insertar", idEncuestaParameter, rolEstablecimientoParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_MuestraGes_ListarEstablecimientos_Result> Pa_Cls_MuestraGes_ListarEstablecimientos(Nullable<int> idEncuesta)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_MuestraGes_ListarEstablecimientos_Result>("Pa_Cls_MuestraGes_ListarEstablecimientos", idEncuestaParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_MuestraGes_ListarGeorreferenciados_Result> Pa_Cls_MuestraGes_ListarGeorreferenciados(Nullable<int> idEncuesta)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_MuestraGes_ListarGeorreferenciados_Result>("Pa_Cls_MuestraGes_ListarGeorreferenciados", idEncuestaParameter);
        }
    
        public virtual int Pa_Cls_MuestraGes_Modificar(Nullable<int> idEncuesta, Nullable<int> rolEstablecimiento, Nullable<System.DateTime> fechaRecepcion, string observacion)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var rolEstablecimientoParameter = rolEstablecimiento.HasValue ?
                new ObjectParameter("RolEstablecimiento", rolEstablecimiento) :
                new ObjectParameter("RolEstablecimiento", typeof(int));
    
            var fechaRecepcionParameter = fechaRecepcion.HasValue ?
                new ObjectParameter("FechaRecepcion", fechaRecepcion) :
                new ObjectParameter("FechaRecepcion", typeof(System.DateTime));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_MuestraGes_Modificar", idEncuestaParameter, rolEstablecimientoParameter, fechaRecepcionParameter, observacionParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_MuestraGes_ReporteDirectorio_Result> Pa_Cls_MuestraGes_ReporteDirectorio(Nullable<int> idEncuesta, Nullable<int> idEstado, Nullable<int> rol, Nullable<int> idLogro)
        {
            var idEncuestaParameter = idEncuesta.HasValue ?
                new ObjectParameter("IdEncuesta", idEncuesta) :
                new ObjectParameter("IdEncuesta", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var rolParameter = rol.HasValue ?
                new ObjectParameter("Rol", rol) :
                new ObjectParameter("Rol", typeof(int));
    
            var idLogroParameter = idLogro.HasValue ?
                new ObjectParameter("IdLogro", idLogro) :
                new ObjectParameter("IdLogro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_MuestraGes_ReporteDirectorio_Result>("Pa_Cls_MuestraGes_ReporteDirectorio", idEncuestaParameter, idEstadoParameter, rolParameter, idLogroParameter);
        }
    
        public virtual int Pa_Cls_PaginasRolesSys_Eliminar(string nombreRol, Nullable<int> idPagina)
        {
            var nombreRolParameter = nombreRol != null ?
                new ObjectParameter("NombreRol", nombreRol) :
                new ObjectParameter("NombreRol", typeof(string));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("IdPagina", idPagina) :
                new ObjectParameter("IdPagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_PaginasRolesSys_Eliminar", nombreRolParameter, idPaginaParameter);
        }
    
        public virtual int Pa_Cls_PaginasRolesSys_Insertar(string nombreRol, Nullable<int> idPagina)
        {
            var nombreRolParameter = nombreRol != null ?
                new ObjectParameter("NombreRol", nombreRol) :
                new ObjectParameter("NombreRol", typeof(string));
    
            var idPaginaParameter = idPagina.HasValue ?
                new ObjectParameter("IdPagina", idPagina) :
                new ObjectParameter("IdPagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_PaginasRolesSys_Insertar", nombreRolParameter, idPaginaParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_ProvinciasGlo_Listar_Result> Pa_Cls_ProvinciasGlo_Listar(Nullable<int> codRegion)
        {
            var codRegionParameter = codRegion.HasValue ?
                new ObjectParameter("CodRegion", codRegion) :
                new ObjectParameter("CodRegion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_ProvinciasGlo_Listar_Result>("Pa_Cls_ProvinciasGlo_Listar", codRegionParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_RegionGlo_Listar_Result> Pa_Cls_RegionGlo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_RegionGlo_Listar_Result>("Pa_Cls_RegionGlo_Listar");
        }
    
        public virtual ObjectResult<string> Pa_Cls_RolesSys_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pa_Cls_RolesSys_Listar");
        }
    
        public virtual ObjectResult<Pa_Cls_SeccionGlo_Listar_Result> Pa_Cls_SeccionGlo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_SeccionGlo_Listar_Result>("Pa_Cls_SeccionGlo_Listar");
        }
    
        public virtual ObjectResult<Pa_Cls_SubClaseGlo_Listar_Result> Pa_Cls_SubClaseGlo_Listar(Nullable<int> idClase)
        {
            var idClaseParameter = idClase.HasValue ?
                new ObjectParameter("IdClase", idClase) :
                new ObjectParameter("IdClase", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_SubClaseGlo_Listar_Result>("Pa_Cls_SubClaseGlo_Listar", idClaseParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_TipoViaGlo_Listar_Result> Pa_Cls_TipoViaGlo_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_TipoViaGlo_Listar_Result>("Pa_Cls_TipoViaGlo_Listar");
        }
    
        public virtual int Pa_Cls_UsuarioGes_Eliminar(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_UsuarioGes_Eliminar", loginParameter);
        }
    
        public virtual int Pa_Cls_UsuarioGes_Insertar(string login, string contrasena, Nullable<int> rutUsuario, string dvUsuario, string nombreUsuario, string email)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var rutUsuarioParameter = rutUsuario.HasValue ?
                new ObjectParameter("RutUsuario", rutUsuario) :
                new ObjectParameter("RutUsuario", typeof(int));
    
            var dvUsuarioParameter = dvUsuario != null ?
                new ObjectParameter("DvUsuario", dvUsuario) :
                new ObjectParameter("DvUsuario", typeof(string));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_UsuarioGes_Insertar", loginParameter, contrasenaParameter, rutUsuarioParameter, dvUsuarioParameter, nombreUsuarioParameter, emailParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_UsuarioGes_Listar_Result> Pa_Cls_UsuarioGes_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_UsuarioGes_Listar_Result>("Pa_Cls_UsuarioGes_Listar");
        }
    
        public virtual int Pa_Cls_UsuarioGes_Modificar(string login, string contrasena, Nullable<int> rutUsuario, string dvUsuario, string nombreUsuario, string email)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var rutUsuarioParameter = rutUsuario.HasValue ?
                new ObjectParameter("RutUsuario", rutUsuario) :
                new ObjectParameter("RutUsuario", typeof(int));
    
            var dvUsuarioParameter = dvUsuario != null ?
                new ObjectParameter("DvUsuario", dvUsuario) :
                new ObjectParameter("DvUsuario", typeof(string));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("NombreUsuario", nombreUsuario) :
                new ObjectParameter("NombreUsuario", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_UsuarioGes_Modificar", loginParameter, contrasenaParameter, rutUsuarioParameter, dvUsuarioParameter, nombreUsuarioParameter, emailParameter);
        }
    
        public virtual ObjectResult<Pa_Cls_UsuarioGes_UsuarioValido_Result> Pa_Cls_UsuarioGes_UsuarioValido(string login, string contrasena)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Cls_UsuarioGes_UsuarioValido_Result>("Pa_Cls_UsuarioGes_UsuarioValido", loginParameter, contrasenaParameter);
        }
    
        public virtual int Pa_Cls_UsuariosEnRoles_Insertar(string login, string nombreRol)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var nombreRolParameter = nombreRol != null ?
                new ObjectParameter("NombreRol", nombreRol) :
                new ObjectParameter("NombreRol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pa_Cls_UsuariosEnRoles_Insertar", loginParameter, nombreRolParameter);
        }
    
        public virtual ObjectResult<Pa_Perfiles_EsRol_Result> Pa_Perfiles_EsRol(string rol, string login)
        {
            var rolParameter = rol != null ?
                new ObjectParameter("Rol", rol) :
                new ObjectParameter("Rol", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Perfiles_EsRol_Result>("Pa_Perfiles_EsRol", rolParameter, loginParameter);
        }
    
        public virtual ObjectResult<Pa_Perfiles_MenuLateral_Result> Pa_Perfiles_MenuLateral(string modulo, string login)
        {
            var moduloParameter = modulo != null ?
                new ObjectParameter("Modulo", modulo) :
                new ObjectParameter("Modulo", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Perfiles_MenuLateral_Result>("Pa_Perfiles_MenuLateral", moduloParameter, loginParameter);
        }
    
        public virtual ObjectResult<Pa_Perfiles_MenuSegunRol_Result> Pa_Perfiles_MenuSegunRol(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Perfiles_MenuSegunRol_Result>("Pa_Perfiles_MenuSegunRol", loginParameter);
        }
    
        public virtual ObjectResult<string> Pa_Perfiles_ModulosListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pa_Perfiles_ModulosListar");
        }
    
        public virtual ObjectResult<Pa_Perfiles_PaginasListar_Result> Pa_Perfiles_PaginasListar(string nombreRol, string modulo)
        {
            var nombreRolParameter = nombreRol != null ?
                new ObjectParameter("NombreRol", nombreRol) :
                new ObjectParameter("NombreRol", typeof(string));
    
            var moduloParameter = modulo != null ?
                new ObjectParameter("Modulo", modulo) :
                new ObjectParameter("Modulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Perfiles_PaginasListar_Result>("Pa_Perfiles_PaginasListar", nombreRolParameter, moduloParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Pa_Perfiles_Permiso(string url, string login)
        {
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pa_Perfiles_Permiso", urlParameter, loginParameter);
        }
    
        public virtual ObjectResult<string> Pa_Perfiles_RolesListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pa_Perfiles_RolesListar");
        }
    
        public virtual ObjectResult<Pa_Perfiles_SubMenuLateral_Result> Pa_Perfiles_SubMenuLateral(Nullable<int> idMenu, string login)
        {
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("IdMenu", idMenu) :
                new ObjectParameter("IdMenu", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pa_Perfiles_SubMenuLateral_Result>("Pa_Perfiles_SubMenuLateral", idMenuParameter, loginParameter);
        }
    }
}
