//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Paginas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Paginas()
        {
            this.Sys_Roles = new HashSet<Sys_Roles>();
        }
    
        public int IdPagina { get; set; }
        public int IdMenu { get; set; }
        public string Descripcion { get; set; }
        public string Url { get; set; }
        public string Identificador { get; set; }
        public string Modulo { get; set; }
    
        public virtual Sys_Menu Sys_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Roles> Sys_Roles { get; set; }
    }
}
